# Generated by Django 5.2.4 on 2025-07-18 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nivel', models.CharField(default='Sin nivel', max_length=20)),
                ('edad', models.IntegerField(default=0)),
                ('tipo_juego', models.CharField(default='Sin tipo', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('dni', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='JugadorCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jugador.categoria')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jugador.jugador')),
            ],
            options={
                'unique_together': {('jugador', 'categoria')},
            },
        ),
        migrations.AddField(
            model_name='jugador',
            name='categorias',
            field=models.ManyToManyField(through='jugador.JugadorCategoria', to='jugador.categoria'),
        ),
    ]
