# Generated by Django 5.2.4 on 2025-07-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='edad',
            field=models.CharField(default=0),
        ),
    ]
