# Generated by Django 5.0.5 on 2024-09-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='categoria',
        ),
        migrations.AddField(
            model_name='categoria',
            name='edad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categoria',
            name='nivel',
            field=models.CharField(default='Sin nivel', max_length=50),
        ),
        migrations.AddField(
            model_name='categoria',
            name='tipo_juego',
            field=models.CharField(default='Sin tipo', max_length=20),
        ),
    ]
