# Generated by Django 5.2.4 on 2025-07-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugador', '0002_alter_categoria_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='edad',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
