# Generated by Django 5.0.5 on 2024-10-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugador', '0002_remove_categoria_categoria_categoria_edad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nivel',
            field=models.IntegerField(default=0),
        ),
    ]
