# Generated by Django 5.0.5 on 2024-11-29 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugador', '0003_alter_categoria_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nivel',
            field=models.CharField(default='Sin nivel', max_length=20),
        ),
    ]
