# Generated by Django 5.2.4 on 2025-07-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugador', '0003_alter_categoria_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='genero',
            field=models.CharField(choices=[('D', 'Damas'), ('C', 'Caballeros'), ('MIX', 'Mixto')], default='C', max_length=10),
        ),
    ]
