# Generated by Django 5.0.5 on 2024-12-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugador', '0004_alter_categoria_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='dni',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='sexo',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1),
        ),
    ]
