# Generated by Django 5.2.4 on 2025-07-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugador', '0004_categoria_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='genero',
            field=models.CharField(default='Sin tipo', max_length=10),
        ),
    ]
