# Generated by Django 5.2.4 on 2025-09-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugador', '0005_alter_categoria_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='estado',
            field=models.CharField(choices=[('ACT', 'Activo'), ('INA', 'Inactivo'), ('DEL', 'Borrado')], db_index=True, default='ACT', max_length=3),
        ),
        migrations.AddField(
            model_name='jugador',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
    ]
