# Generated by Django 5.2.4 on 2025-09-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugador', '0006_jugador_estado_jugador_fecha_baja'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='observaciones',
            field=models.CharField(blank=True, default='Sin observaciones', max_length=200),
        ),
    ]
