# Generated by Django 5.2.4 on 2025-07-18 19:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jugador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancha', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('fecha_inicio', models.DateField(default=datetime.date(2024, 1, 1))),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('Mixto', 'Mixto')], default='Mixto', max_length=6)),
                ('tipo_juego', models.CharField(choices=[('Single', 'Single'), ('Doble', 'Doble')], default='Single', max_length=10)),
                ('anio', models.PositiveIntegerField(default=2025, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('jugador1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_como_jugador1', to='jugador.jugador')),
                ('jugador2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_como_jugador2', to='jugador.jugador')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='torneo.torneo')),
            ],
            options={
                'unique_together': {('jugador1', 'jugador2', 'torneo')},
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('jornada', models.IntegerField()),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo.cancha')),
                ('equipo1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidos_equipo1', to='torneo.equipo')),
                ('equipo2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidos_equipo2', to='torneo.equipo')),
                ('jugador1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidos_jugador1', to='jugador.jugador')),
                ('jugador2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidos_jugador2', to='jugador.jugador')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo.torneo')),
            ],
        ),
        migrations.CreateModel(
            name='PartidoCancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo.cancha')),
                ('id_partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo.partido')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set1_jugador1', models.IntegerField(blank=True, null=True)),
                ('set1_jugador2', models.IntegerField(blank=True, null=True)),
                ('set2_jugador1', models.IntegerField(blank=True, null=True)),
                ('set2_jugador2', models.IntegerField(blank=True, null=True)),
                ('set3_jugador1', models.IntegerField(blank=True, null=True)),
                ('set3_jugador2', models.IntegerField(blank=True, null=True)),
                ('set1_equipo1', models.IntegerField(blank=True, null=True)),
                ('set1_equipo2', models.IntegerField(blank=True, null=True)),
                ('set2_equipo1', models.IntegerField(blank=True, null=True)),
                ('set2_equipo2', models.IntegerField(blank=True, null=True)),
                ('set3_equipo1', models.IntegerField(blank=True, null=True)),
                ('set3_equipo2', models.IntegerField(blank=True, null=True)),
                ('ganador_equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_ganados', to='torneo.equipo')),
                ('ganador_jugador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_ganados', to='jugador.jugador')),
                ('partido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='torneo.partido')),
            ],
        ),
        migrations.AddField(
            model_name='cancha',
            name='sede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canchas', to='torneo.sede'),
        ),
        migrations.CreateModel(
            name='HistorialJornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('partidos', models.ManyToManyField(to='torneo.partido')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo.torneo')),
            ],
        ),
        migrations.CreateModel(
            name='TorneoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_torneos', to='jugador.categoria')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torneo_categorias', to='torneo.torneo')),
            ],
        ),
        migrations.AddField(
            model_name='torneo',
            name='categorias',
            field=models.ManyToManyField(related_name='torneos', through='torneo.TorneoCategoria', to='jugador.categoria'),
        ),
        migrations.CreateModel(
            name='TorneoJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugador_torneos', to='jugador.jugador')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torneo_jugadores', to='torneo.torneo')),
            ],
        ),
        migrations.CreateModel(
            name='MasterJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jugador.categoria')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jugador.jugador')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo.torneo')),
            ],
            options={
                'ordering': ['posicion'],
                'unique_together': {('torneo', 'jugador', 'categoria')},
            },
        ),
        migrations.AddConstraint(
            model_name='torneocategoria',
            constraint=models.UniqueConstraint(fields=('torneo', 'categoria'), name='unique_torneo_categoria'),
        ),
        migrations.AlterUniqueTogether(
            name='torneojugador',
            unique_together={('torneo', 'jugador')},
        ),
    ]
