# Generated by Django 5.0.5 on 2024-08-13 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jugador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='partido',
            fields=[
                ('id_partido', models.AutoField(primary_key=True, serialize=False)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jugador.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='enfrentamiento',
            fields=[
                ('id_enfrentamiento', models.AutoField(primary_key=True, serialize=False)),
                ('id_jugador1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfrentamientos_como_jugador1', to='jugador.jugador')),
                ('id_jugador2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfrentamientos_como_jugador2', to='jugador.jugador')),
                ('id_partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo.partido')),
            ],
        ),
        migrations.CreateModel(
            name='resultadoPartido',
            fields=[
                ('id_resultado', models.AutoField(primary_key=True, serialize=False)),
                ('resultado1', models.IntegerField()),
                ('resultado2', models.IntegerField()),
                ('id_jugador1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_como_jugador1', to='jugador.jugador')),
                ('id_jugador2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_como_jugador2', to='jugador.jugador')),
                ('id_partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo.enfrentamiento')),
            ],
        ),
    ]
