# Generated by Django 5.2.4 on 2025-09-12 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='torneo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='torneo.torneo'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='equipo1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_equipo1', to='torneo.equipo'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='equipo2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_equipo2', to='torneo.equipo'),
        ),
    ]
