# Generated by Django 5.0.5 on 2024-10-11 20:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancha', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('anio', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)])),
            ],
        ),
        migrations.AddField(
            model_name='partido',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='partido',
            name='hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='PartidoCancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo.cancha')),
                ('id_partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo.partido')),
            ],
        ),
        migrations.AddField(
            model_name='partido',
            name='id_cancha',
            field=models.ManyToManyField(through='torneo.PartidoCancha', to='torneo.cancha'),
        ),
        migrations.AddField(
            model_name='partido',
            name='id_torneo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='torneo.torneo'),
            preserve_default=False,
        ),
    ]
