# Generated by Django 5.0.5 on 2024-10-12 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0002_cancha_torneo_partido_fecha_partido_hora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='torneo',
            name='fecha_inicio',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
