# Generated by Django 5.2.4 on 2025-09-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0002_alter_equipo_torneo_alter_partido_equipo1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='description',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='descripción'),
        ),
    ]
