# Generated by Django 5.0.5 on 2024-10-12 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugador', '0003_alter_categoria_nivel'),
        ('torneo', '0003_torneo_fecha_fin_torneo_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torneo',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='torneo',
            name='categoria',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, to='jugador.categoria'),
        ),
    ]
