# Generated by Django 5.0.5 on 2024-11-06 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0004_remove_torneo_ubicacion_torneo_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='anio',
            field=models.PositiveIntegerField(default=2024),
        ),
    ]
