# Generated by Django 5.0.5 on 2024-11-14 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugador', '0003_alter_categoria_nivel'),
        ('torneo', '0005_alter_torneo_anio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultadopartido',
            name='id_partido',
        ),
        migrations.RemoveField(
            model_name='resultadopartido',
            name='id_jugador1',
        ),
        migrations.RemoveField(
            model_name='resultadopartido',
            name='id_jugador2',
        ),
        migrations.RemoveField(
            model_name='torneo',
            name='categoria',
        ),
        migrations.CreateModel(
            name='TorneoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jugador.categoria')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo.torneo')),
            ],
        ),
        migrations.AddField(
            model_name='torneo',
            name='categorias',
            field=models.ManyToManyField(through='torneo.TorneoCategoria', to='jugador.categoria'),
        ),
        migrations.DeleteModel(
            name='enfrentamiento',
        ),
        migrations.DeleteModel(
            name='resultadoPartido',
        ),
    ]
