# Generated by Django 5.0.5 on 2024-11-27 23:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0006_remove_resultadopartido_id_partido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='torneo',
            name='anio',
            field=models.PositiveIntegerField(default=2024, editable=False),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date(2024, 1, 1)),
        ),
        migrations.AlterField(
            model_name='partido',
            name='id_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo.categoria'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='categorias',
            field=models.ManyToManyField(through='torneo.TorneoCategoria', to='torneo.categoria'),
        ),
        migrations.AlterField(
            model_name='torneocategoria',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo.categoria'),
        ),
    ]
