# Generated by Django 5.0.5 on 2024-11-27 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugador', '0003_alter_categoria_nivel'),
        ('torneo', '0007_categoria_alter_torneo_anio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='id_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jugador.categoria'),
        ),
        migrations.AlterField(
            model_name='torneocategoria',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_torneos', to='jugador.categoria'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='categorias',
            field=models.ManyToManyField(related_name='torneos', through='torneo.TorneoCategoria', to='jugador.categoria'),
        ),
        migrations.AlterField(
            model_name='torneocategoria',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torneo_categorias', to='torneo.torneo'),
        ),
        migrations.AlterUniqueTogether(
            name='torneocategoria',
            unique_together={('torneo', 'categoria')},
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
