# Generated by Django 5.0.5 on 2024-11-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugador', '0003_alter_categoria_nivel'),
        ('torneo', '0008_alter_partido_id_categoria_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='torneocategoria',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='torneocategoria',
            constraint=models.UniqueConstraint(fields=('torneo', 'categoria'), name='unique_torneo_categoria'),
        ),
    ]
