# Generated by Django 5.0.5 on 2024-11-29 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugador', '0004_alter_categoria_nivel'),
        ('torneo', '0009_alter_torneocategoria_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TorneoJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugador_torneos', to='jugador.jugador')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torneo_jugadores', to='torneo.torneo')),
            ],
            options={
                'unique_together': {('torneo', 'jugador')},
            },
        ),
    ]
