# Generated by Django 5.0.5 on 2024-12-02 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0010_torneojugador'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='tipo',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('Mixto', 'Mixto')], default='Mixto', editable=False, max_length=6),
        ),
    ]
