# Generated by Django 5.0.5 on 2024-12-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0011_torneo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='tipo',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('Mixto', 'Mixto')], default='Mixto', max_length=6),
        ),
    ]
