# Generated by Django 5.0.5 on 2024-08-13 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jugador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id_ranking', models.AutoField(primary_key=True, serialize=False)),
                ('posicion', models.IntegerField()),
                ('pj', models.IntegerField()),
                ('pg', models.IntegerField()),
                ('puntaje_total_categoria', models.IntegerField()),
                ('puntaje_acumulador', models.IntegerField()),
                ('bimestre', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jugador.categoria')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jugador.jugador')),
            ],
            options={
                'unique_together': {('jugador', 'bimestre', 'anio', 'categoria')},
            },
        ),
    ]
