# Generated by Django 5.2.4 on 2025-07-18 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jugador', '0001_initial'),
        ('torneo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id_ranking', models.AutoField(primary_key=True, serialize=False)),
                ('posicion', models.IntegerField(default=0)),
                ('pj', models.IntegerField(default=0)),
                ('pg', models.IntegerField(default=0)),
                ('pp', models.IntegerField(default=0)),
                ('sets', models.IntegerField(default=0)),
                ('games', models.IntegerField(default=0)),
                ('puntaje_total_categoria', models.IntegerField(default=0)),
                ('puntaje_acumulador', models.IntegerField(default=0)),
                ('bimestre', models.IntegerField(default=0)),
                ('anio', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jugador.categoria')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jugador.jugador')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='torneo.torneo')),
            ],
            options={
                'unique_together': {('torneo', 'jugador', 'bimestre', 'anio', 'categoria')},
            },
        ),
        migrations.CreateModel(
            name='RankingEquipo',
            fields=[
                ('id_ranking_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('posicion', models.IntegerField(default=0)),
                ('pj', models.IntegerField(default=0)),
                ('pg', models.IntegerField(default=0)),
                ('pp', models.IntegerField(default=0)),
                ('sets', models.IntegerField(default=0)),
                ('games', models.IntegerField(default=0)),
                ('puntaje_total_categoria', models.IntegerField(default=0)),
                ('puntaje_acumulador', models.IntegerField(default=0)),
                ('bimestre', models.IntegerField(default=0)),
                ('anio', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jugador.categoria')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo.equipo')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings_equipos', to='torneo.torneo')),
            ],
            options={
                'unique_together': {('torneo', 'equipo', 'bimestre', 'anio', 'categoria')},
            },
        ),
    ]
