# Generated by Django 5.2.4 on 2025-08-14 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugador', '0005_alter_categoria_genero'),
        ('ranking', '0002_alter_ranking_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='categoria',
            field=models.ForeignKey(default=19, on_delete=django.db.models.deletion.CASCADE, to='jugador.categoria'),
        ),
        migrations.AlterField(
            model_name='rankingequipo',
            name='categoria',
            field=models.ForeignKey(default=19, on_delete=django.db.models.deletion.CASCADE, to='jugador.categoria'),
        ),
    ]
